use std::{
    fs,
    path::{Path, PathBuf},
};

use crate::{
    backend::{BackendBundle, build_backend_bundle},
    resolver::LocatedDiagnostic,
};

#[derive(Debug, Clone)]
pub struct JavaBackendOptions {
    pub output_dir: PathBuf,
}

impl JavaBackendOptions {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct JavaBackendResult {
    pub diagnostics: Vec<LocatedDiagnostic>,
    pub written_files: Vec<PathBuf>,
}

pub fn generate_java_path(
    path: impl AsRef<Path>,
    options: JavaBackendOptions,
) -> Result<JavaBackendResult, String> {
    let bundled = build_backend_bundle(path)?;
    if !bundled.diagnostics.is_empty() {
        return Ok(JavaBackendResult {
            diagnostics: bundled.diagnostics,
            written_files: Vec::new(),
        });
    }

    let bundle = bundled
        .bundle
        .expect("backend bundle after successful build");
    fs::create_dir_all(&options.output_dir)
        .map_err(|err| format!("create {}: {err}", options.output_dir.display()))?;

    let marker_path = options.output_dir.join("LumeGenerated.java");
    fs::write(&marker_path, render_marker_source(&bundle))
        .map_err(|err| format!("write {}: {err}", marker_path.display()))?;

    Ok(JavaBackendResult {
        diagnostics: Vec::new(),
        written_files: vec![marker_path],
    })
}

fn render_marker_source(bundle: &BackendBundle) -> String {
    let module_name = bundle.ir.module.as_deref().unwrap_or("<default>");
    let source_path = escape_comment_text(&bundle.root_display_path);

    format!(
        concat!(
            "// Generated by Lume Java backend.\n",
            "// Source: {source_path}\n",
            "// Module: {module_name}\n",
            "// Types: {type_count}\n",
            "// Functions: {function_count}\n",
            "// Globals: {global_count}\n",
            "final class LumeGenerated {{\n",
            "    private LumeGenerated() {{}}\n",
            "}}\n"
        ),
        source_path = source_path,
        module_name = escape_comment_text(module_name),
        type_count = bundle.descriptors.types.len(),
        function_count = bundle.descriptors.functions.len(),
        global_count = bundle.descriptors.globals.len(),
    )
}

fn escape_comment_text(text: &str) -> String {
    text.replace("*/", "* /")
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::*;

    #[test]
    fn generates_marker_java_file_for_checked_program() {
        let temp = temp_path("lume-java-generate");
        let source = temp.join("main.lum");
        let out = temp.join("out");
        fs::create_dir_all(&temp).expect("create temp dir");
        fs::write(
            &source,
            r#"
def main() {
    println("hello")
}
"#,
        )
        .expect("write source");

        let result = generate_java_path(&source, JavaBackendOptions::new(&out)).expect("generate");

        assert!(result.diagnostics.is_empty());
        assert_eq!(result.written_files.len(), 1);
        let marker = fs::read_to_string(&result.written_files[0]).expect("read marker");
        assert!(marker.contains("Generated by Lume Java backend."));
        assert!(marker.contains("final class LumeGenerated"));

        let _ = fs::remove_dir_all(temp);
    }

    #[test]
    fn does_not_write_java_when_lume_has_diagnostics() {
        let temp = temp_path("lume-java-invalid");
        let source = temp.join("broken.lum");
        let out = temp.join("out");
        fs::create_dir_all(&temp).expect("create temp dir");
        fs::write(&source, "def main() { missing() }").expect("write source");

        let result = generate_java_path(&source, JavaBackendOptions::new(&out)).expect("generate");

        assert!(!result.diagnostics.is_empty());
        assert!(result.written_files.is_empty());
        assert!(!out.exists());

        let _ = fs::remove_dir_all(temp);
    }

    fn temp_path(prefix: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time after epoch")
            .as_nanos();
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        manifest_dir
            .parent()
            .and_then(|crates_dir| crates_dir.parent())
            .expect("rust workspace root")
            .join("target")
            .join(format!("{prefix}-{nanos}"))
    }
}
